# Default settings for Report Formats
# ============================================
# This contains the default for different settings.

format:
  html:
    body_begin: <body>
    body_end: </body>
    style:
      - webobjects/default.css
