# Default settings for Report Formats
# ============================================
# This contains the default for different settings.

format:
  html:
    body_begin: <body>
    body_end: |+
      <div id="footer"><a href="/">Alinex WebObjects</a> Version 0.1 by <em>Alexander Schilling</em></div>
      </body>
    style:
      - webobjects/default.css
    compress: true
